# Generated by Django 4.2.13 on 2024-10-01 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Memento', '0002_userpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_registrations', models.PositiveIntegerField(default=0)),
                ('countdown_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_count', models.PositiveIntegerField(default=74)),
                ('max_visitors', models.PositiveIntegerField(default=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
