# Generated by Django 4.2.13 on 2024-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memento', '0004_counter_delete_registrationcounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.PositiveIntegerField(default=81),
        ),
    ]
