# Generated by Django 4.2.13 on 2024-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memento', '0005_alter_counter_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=46800)),
            ],
        ),
    ]
